name: genomics_full
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - admixture=1.3.0=0
  - aioeasywebdav=2.4.0=py39hf3d152e_1001
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py39heb7d2ae_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.11=hd590300_1
  - amply=0.1.6=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attr=2.5.2=h39aace5_0
  - attrs=25.3.0=pyh71513ae_0
  - bcftools=1.19=h8b25389_1
  - bcrypt=4.3.0=py39h20260ba_1
  - beagle=5.5_27Feb25.75f=hdfd78af_0
  - bedtools=2.31.1=hf5e1c6e_2
  - binutils_impl_linux-64=2.45=bootstrap_h59bd682_4
  - bioconductor-lea=3.18.0=r44h3df3fcb_0
  - biopython=1.85=py39h8cd3c5a_1
  - blast=2.16.0=hc155240_3
  - boto3=1.40.13=pyhd8ed1ab_0
  - botocore=1.40.13=pyge39_1234567_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.0.9=py39h5a03fae_8
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cachetools=5.5.2=pyhd8ed1ab_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - coin-or-cbc=2.10.12=h8b142ea_1
  - coin-or-cgl=0.60.7=h516709c_0
  - coin-or-clp=1.17.8=h1ee7a9c_0
  - coin-or-osi=0.108.10=haf5fa05_0
  - coin-or-utils=2.11.11=hee58242_0
  - coincbc=2.10.12=4_metapackage
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - conda-gcc-specs=15.2.0=h53410ce_16
  - configargparse=1.7.1=pyhe01879c_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - contourpy=1.3.0=py39h74842e3_2
  - cryptography=45.0.6=py39hb2f7f84_0
  - curl=8.8.0=he654da7_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - dadi=2.4.3=py39hf4f1cb0_0
  - datrie=0.8.2=py39h8cd3c5a_8
  - dbus=1.13.6=h5008d03_3
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - demes=0.2.3=pyhd8ed1ab_1
  - dmd=2.065.0=1
  - docutils=0.22=pyhd8ed1ab_0
  - dpath=2.2.0=pyha770c72_0
  - dropbox=12.0.2=pyhd8ed1ab_1
  - eido=0.2.4=pyhd8ed1ab_0
  - entrez-direct=22.4=he881be0_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - expat=2.7.3=hecca717_0
  - fastsimcoal2=27093=hdfd78af_0
  - filechunkio=1.8=py_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.59.1=py39heb7d2ae_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.16=hb03c661_0
  - frozenlist=1.7.0=py39h53edacf_0
  - ftputil=5.1.0=pyhd8ed1ab_0
  - gcc=15.2.0=h0dff253_16
  - gcc_impl_linux-64=15.2.0=hc5723f1_16
  - gfortran_impl_linux-64=15.2.0=h281d09f_16
  - giflib=5.2.2=hd590300_0
  - git=2.45.1=pl5321hef9f9f3_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - gnuplot=5.0.3=4
  - google-api-core=2.25.1=pyhd8ed1ab_0
  - google-api-python-client=2.179.0=pyhff2d567_0
  - google-auth=2.40.3=pyhd8ed1ab_0
  - google-auth-httplib2=0.2.0=pyhd8ed1ab_1
  - google-cloud-core=2.4.3=pyhd8ed1ab_0
  - google-cloud-storage=3.3.0=pyhd8ed1ab_0
  - google-crc32c=1.7.1=py39h2cad9fb_0
  - google-resumable-media=2.7.2=pyhd8ed1ab_2
  - googleapis-common-protos=1.70.0=pyhd8ed1ab_0
  - graphite2=1.3.14=hecca717_2
  - grpcio=1.46.3=py39h7fbbf82_0
  - gsl=2.7=he838d99_0
  - gst-plugins-base=1.24.4=h9ad1361_0
  - gstreamer=1.24.4=haf2f30d_0
  - gxx=15.2.0=h76987e4_16
  - gxx_impl_linux-64=15.2.0=hda75c37_16
  - harfbuzz=9.0.0=hfac3d4d_0
  - htslib=1.21=h5efdd21_0
  - httplib2=0.22.0=pyhd8ed1ab_1
  - humanfriendly=10.0=pyh707e725_8
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - invoke=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - k8=0.2.5=hdcf5f25_4
  - kernel-headers_linux-64=4.18.0=he073ed8_9
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_4
  - lerc=4.0.0=h0aef613_1
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang13=18.1.7=default_h087397f_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.8.0=hca28451_1
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libflac=1.5.0=he200343_1
  - libgcc=15.2.0=he0feb66_16
  - libgcc-devel_linux-64=15.2.0=hcc6f6b0_116
  - libgcc-ng=15.2.0=h69a702a_16
  - libgd=2.3.3=h119a65a_9
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.80.2=hf974151_0
  - libgomp=15.2.0=he0feb66_16
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblapacke=3.11.0=5_h6ae95b6_openblas
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm18=18.1.7=hb77312f_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hb9d3cd8_1
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopus=1.5.2=hd0c01bc_0
  - libpng=1.6.43=h2797004_0
  - libpq=16.11=hc183893_2
  - libsanitizer=15.2.0=h90f66d4_16
  - libsndfile=1.2.2=hc7d488a_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-devel_linux-64=15.2.0=hd446a21_116
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libsystemd0=257.10=hd0affe5_3
  - libtiff=4.6.0=h1dd3fc0_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.41.2=h5347b49_1
  - libvorbis=1.3.7=h54a6638_2
  - libwebp=1.4.0=h2c329e2_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxml2=2.12.7=hc051c1a_1
  - libzlib=1.2.13=h4ab18f5_6
  - logmuse=0.2.8=pyhd8ed1ab_1
  - make=4.4.1=hb9d3cd8_2
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py39h9399b63_1
  - matplotlib=3.9.1=py39hf3d152e_1
  - matplotlib-base=3.9.1=py39h0565ad7_2
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minimap2=2.28=he4a0461_3
  - mpg123=1.32.9=hc50e24c_0
  - msmc2=2.1.4=hdfd78af_0
  - multidict=6.6.3=py39h9399b63_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=8.3.0=hf1915f5_4
  - mysql-libs=8.3.0=hca2cd23_4
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncbi-vdb=3.3.0=h9948957_0
  - ncurses=6.5=h2d0b736_3
  - nlopt=2.10.0=py39hca4a52a_0
  - nspr=4.38=h29cc59b_0
  - nss=3.100=hca3bf56_0
  - numpy=2.0.2=py39h9cb892a_1
  - oauth2client=4.1.3=pyhd8ed1ab_1
  - openjdk=21.0.3=hb622114_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py39h1b6b32d_0
  - pango=1.54.0=h4c5309f_1
  - paramiko=4.0.0=pyhd8ed1ab_0
  - pcre2=10.43=hcad00b1_0
  - pephubclient=0.4.4=pyhd8ed1ab_1
  - peppy=0.40.7=pyhd8ed1ab_2
  - perl=5.32.1=7_hd590300_perl5
  - perl-archive-tar=3.04=pl5321hdfd78af_0
  - perl-carp=1.38=pl5321hdfd78af_4
  - perl-common-sense=3.75=pl5321hdfd78af_0
  - perl-compress-raw-bzip2=2.214=pl5321hda65f42_0
  - perl-compress-raw-zlib=2.214=pl5321h4dac143_0
  - perl-encode=3.19=pl5321hec16e2b_1
  - perl-exporter=5.72=pl5321hdfd78af_2
  - perl-exporter-tiny=1.002002=pl5321hdfd78af_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-io-compress=2.214=pl5321h503566f_0
  - perl-io-zlib=1.15=pl5321hdfd78af_1
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.04=pl5321h9948957_0
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_5
  - perl-parent=0.236=pl5321hdfd78af_2
  - perl-pathtools=3.75=pl5321hec16e2b_3
  - perl-scalar-list-utils=1.62=pl5321hec16e2b_1
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - pillow=10.3.0=py39h90c7501_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - plac=1.4.5=pyhd8ed1ab_0
  - platformdirs=4.3.8=pyhe01879c_0
  - plink=1.90b7.7=h7b50bb2_0
  - pluggy=1.6.0=pyhf9edf01_1
  - ply=3.11=pyhd8ed1ab_3
  - prettytable=3.16.0=pyhd8ed1ab_0
  - propcache=0.3.1=py39h9399b63_0
  - proto-plus=1.26.1=pyhd8ed1ab_0
  - protobuf=5.28.3=py39hf88036b_0
  - psmc=0.6.5=h43eeafb_3
  - psutil=7.0.0=py39h8cd3c5a_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulp=2.7.0=py39hf3d152e_1
  - pulseaudio-client=17.0=hb77b528_0
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py39h20260ba_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynacl=1.5.0=py39h8cd3c5a_4
  - pyopenssl=25.1.0=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pyqt=5.15.9=py39h52134e7_5
  - pyqt5-sip=12.12.2=py39h3d6467e_5
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.4.1=pyhd8ed1ab_0
  - python=3.9.19=h0755675_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-irodsclient=3.1.1=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyvcf=0.6.8=py39hf3d152e_1003
  - pyyaml=6.0.2=py39h9399b63_2
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.8=hc9dc06e_21
  - r-base=4.4.0=h019f4a6_1
  - rapidnj=2.3.2=h9948957_6
  - readline=8.3=h853b02a_0
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_1
  - rich=14.1.0=pyhe01879c_0
  - rpds-py=0.27.0=py39h17f49b6_0
  - rpsbproc=0.5.0=h6a68c12_1
  - rsa=4.9.1=pyhd8ed1ab_0
  - ruamel.yaml=0.18.15=py39hd399759_0
  - ruamel.yaml.clib=0.2.8=py39h8cd3c5a_1
  - s3transfer=0.13.1=pyhd8ed1ab_0
  - samtools=1.21=h50ea8bc_0
  - scipy=1.13.1=py39haf93ffa_0
  - sed=4.9=h6688a6e_0
  - seqtk=1.4=he4a0461_2
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - sip=6.7.12=py39h3d6467e_0
  - six=1.17.0=pyhe01879c_1
  - slacker=0.14.0=pyhd8ed1ab_1
  - slim=5.1=hecca717_0
  - smart_open=7.3.0.post1=pyhe01879c_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snakemake=7.32.4=hdfd78af_1
  - snakemake-minimal=7.32.4=pyhdfd78af_1
  - snpeff=5.4.0a=hdfd78af_0
  - sra-tools=2.9.6=hf484d3e_0
  - stone=3.3.2=pyhd8ed1ab_0
  - stopit=1.1.2=pyhd8ed1ab_1
  - sysroot_linux-64=2.28=h4ee821c_9
  - tabulate=0.9.0=pyhd8ed1ab_2
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8d826fa_7
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - toposort=1.10=pyhd8ed1ab_1
  - tornado=6.5.2=py39hd399759_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.16.1=pyhc167863_0
  - typer-slim=0.16.1=pyhe01879c_0
  - typer-slim-standard=0.16.1=h810d63d_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025c=h8577fbf_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - unzip=6.0=hb03c661_4
  - uritemplate=4.2.0=pyhd8ed1ab_0
  - urllib3=1.26.19=pyhd8ed1ab_0
  - vcftools=0.1.16=pl5321hdcf5f25_11
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wget=1.21.4=hda4d442_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.3=py39hd399759_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-libxtst=1.2.5=h4bc722e_0
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - yarl=1.20.1=py39h9399b63_0
  - yte=1.8.1=pyha770c72_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - seaborn==0.13.2
prefix: /home/shestun/miniconda3/envs/genomics_full
