name: genomics_full
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Workflow
  - python=3.9
  - snakemake=7.32.4
  
  # Bioinformatics Tools
  - bcftools=1.19
  - plink=1.90b6.21  # Убедитесь, что версия поддерживает --allow-extra-chr
  - snpeff=5.1
  - blast=2.15.0
  - samtools=1.19
  - vcftools=0.1.16
  
  # Simulation & Analysis
  - dadi=2.4.3
  - slim=4.0.1      # Укажите корректную версию SLiM (часто в bioconda она старая, мб придется компилировать или искать канал)
  - bioconductor-lea # Для sNMF
  
  # Python Libs for Scripts
  - pandas
  - matplotlib
  - seaborn
  - numpy
  - scipy
  - cyvcf2          # Быстрый парсинг VCF
  - biopython
  
  # R Environment
  - r-base=4.3
