samples:
  population_name: "Spoonbill"

resources:
  # === ИСПРАВЛЕННЫЕ ПУТИ (согласно вашему ls) ===
  # Основной файл вариантов
  vcf: "resources/CalidrisPygmaea.vcf"
  
  # Референсный геном
  genome: "resources/CalidrisPygmaea.fasta"
  
  # Аннотация генов
  genes: "resources/CalidrisPygmaea.gff"

  # Путь к внешней группе. 
  # Добавляем путь к самому геному турухтана
  outgroup_genome: "resources/CalidrisPugnax.fna"
  # Этот файл будет создан автоматически
  outgroup_vcf: "results/load/outgroup_mapped.vcf.gz"
  
  # Ссылки на эталонные половые хромосомы (Зебровая амадина и Курица) для определения пола
  ref_Z_url: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/957/565/GCF_003957565.2_bTaeGut1.4.pri/GCF_003957565.2_bTaeGut1.4.pri_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrZ.fna.gz"
  ref_W_url: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/002/315/GCF_000002315.6_GRCg6a/GCF_000002315.6_GRCg6a_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/chrW.fna.gz"

filtering:
  # Базовое качество
  qual: 30
  
  # Глубина покрытия (Depth). 
  # ВАЖНО: Эти значения лучше уточнить скриптом calc_thresholds.py
  min_depth: 100
  max_depth: 600
  
  # Доля пропущенных данных (разрешаем не более 5% пропусков)
  max_missing: 0.95
  
  # Харди-Вайнберг
  hwe_threshold: "1e-5"
  
  # === ПАРАМЕТРЫ, КОТОРЫХ НЕ ХВАТАЛО ===
  # Баланс аллелей (для отсева паралогов у гетерозигот)
  min_allele_balance: 0.2
  # Расстояние между SNP (для удаления сцепленных инделов)
  snp_gap: 5

demography:
  # Скорость мутирования (стандарт для птиц ~1.33e-8 или 4.6e-9)
  mu: 1.33e-8
  # Время генерации (лет)
  gen_time: 4
  # Параметры для PSMC (если будете запускать для отдельных бамов)
  psmc:
    pattern: "4+25*2+4+6"

inbreeding_roh:
  # Параметры поиска участков гомозиготности
  min_kb: 100       # Минимальная длина участка (кб)
  min_snps: 25      # Минимальное число SNP в участке

window_stats:
  # Размер окна для Pi и Tajima's D
  window_size: 50000

snmf:
  # Параметры для анализа структуры популяции
  K_min: 1
  K_max: 5
  repetitions: 5

dadi:
  # Проекция выборки (должна быть чуть меньше удвоенного числа особей)
  projections: [20]
  bootstraps: 50
